# Generated by Django 4.2.5 on 2023-10-06 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0002_alter_log_idusuario_alter_usuario_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.CharField(max_length=500)),
                ('Tiempo', models.DateTimeField(auto_now_add=True)),
                ('IDEmisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='IDEmisor', to='registro.usuario')),
                ('IDReceptor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='IDReceptor', to='registro.usuario')),
            ],
            options={
                'db_table': 'Mensajea',
            },
        ),
    ]
