# Generated by Django 4.2.5 on 2023-10-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_usuario_contactos_alter_log_idusuario_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajea',
            name='IDEmisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Enviados', to='registro.usuario'),
        ),
        migrations.AlterField(
            model_name='mensajea',
            name='IDReceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Recibidos', to='registro.usuario'),
        ),
    ]
