# Generated by Django 4.2.5 on 2023-10-08 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_usuario_contactos_alter_log_idusuario_and_more'),
        ('chat', '0002_alter_mensajea_idemisor_alter_mensajea_idreceptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('IDInformacion', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Informacion',
            },
        ),
        migrations.CreateModel(
            name='Responde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregunta', to='chat.informacion')),
                ('IDRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Respuesta', to='chat.informacion')),
            ],
            options={
                'db_table': 'Responde',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDInformacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.informacion')),
                ('IDUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro.usuario')),
            ],
            options={
                'db_table': 'Consulta',
            },
        ),
    ]
