# Generated by Django 4.2.5 on 2023-10-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_informacion_responde_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='texto',
            field=models.CharField(max_length=5000),
        ),
    ]
