# Generated by Django 4.2.5 on 2023-10-22 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_usuario_contactos_alter_log_idusuario_and_more'),
        ('chat', '0005_delete_mensajea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('IDPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('Pregunta', models.CharField(max_length=1000)),
                ('Respuesta', models.CharField(max_length=5000)),
                ('IDUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Preguntas', to='registro.usuario')),
            ],
            options={
                'db_table': 'Pregunta',
            },
        ),
        migrations.RemoveField(
            model_name='responde',
            name='IDPregunta',
        ),
        migrations.RemoveField(
            model_name='responde',
            name='IDRespuesta',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Informacion',
        ),
        migrations.DeleteModel(
            name='Responde',
        ),
    ]
