# Generated by Django 4.2.5 on 2023-10-11 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_remove_usuario_contactos_alter_log_idusuario_and_more'),
        ('denuncia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('IDActor', models.AutoField(primary_key=True, serialize=False)),
                ('CI', models.IntegerField()),
                ('Nombre', models.CharField(max_length=75)),
                ('Apellido', models.CharField(max_length=75)),
                ('FechaNacimiento', models.DateField()),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=150)),
                ('Nacionalidad', models.CharField(max_length=50)),
                ('EstadoCivil', models.CharField(max_length=30)),
                ('Sexo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Actor',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('IDDenuncia', models.AutoField(primary_key=True, serialize=False)),
                ('FechaHecho', models.DateTimeField()),
                ('Lugar', models.CharField(max_length=150)),
                ('Frecuencia', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=5000)),
                ('FechaDenuncia', models.DateTimeField(auto_now_add=True)),
                ('IDDenunciante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Denuncias', to='registro.usuario')),
            ],
            options={
                'db_table': 'Denuncia',
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Ocupacion',
            },
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departamento', models.CharField(max_length=30)),
                ('Zona', models.CharField(max_length=30)),
                ('Ingresos', models.CharField(max_length=30)),
                ('AsistenciaMedica', models.CharField(max_length=2)),
                ('NivelEducativo', models.CharField(max_length=30)),
                ('IDActor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Victima', to='denuncia.actor')),
            ],
            options={
                'db_table': 'Victima',
            },
        ),
        migrations.CreateModel(
            name='TieneDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCategoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Denuncias', to='denuncia.categoria')),
                ('IDDenuncia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Categorias', to='denuncia.denuncia')),
            ],
            options={
                'db_table': 'TieneDC',
            },
        ),
        migrations.CreateModel(
            name='Testigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonio', models.CharField(max_length=5000)),
                ('IDActor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Testigo', to='denuncia.actor')),
            ],
            options={
                'db_table': 'Testigo',
            },
        ),
        migrations.CreateModel(
            name='Implica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDActor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Denuncias', to='denuncia.actor')),
                ('IDDenuncia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Actores', to='denuncia.denuncia')),
            ],
            options={
                'db_table': 'Implica',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('IDEvidencia', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('IDDenuncia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Evidencias', to='denuncia.denuncia')),
            ],
            options={
                'db_table': 'Evidencia',
            },
        ),
        migrations.CreateModel(
            name='Agresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=500)),
                ('RelacionVictima', models.CharField(max_length=50)),
                ('IDActor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Agresor', to='denuncia.actor')),
            ],
            options={
                'db_table': 'Agresor',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='Ocupacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Actores', to='denuncia.ocupacion'),
        ),
    ]
