# Generated by Django 4.2.5 on 2023-10-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0002_actor_denuncia_ocupacion_victima_tienedc_testigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='Ocupacion',
            field=models.CharField(max_length=30),
        ),
    ]
