# Generated by Django 4.2.5 on 2023-10-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0003_alter_actor_ocupacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='Frecuencia',
            field=models.CharField(max_length=100),
        ),
    ]
