# Generated by Django 4.2.5 on 2023-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0004_alter_denuncia_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='Zona',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
