# Generated by Django 4.2.5 on 2023-10-06 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('Telefono', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('IDRol', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Tiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Relacion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Tiene',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Apellido', models.TextField(max_length=45)),
                ('Nombre', models.TextField(max_length=45)),
                ('Alias', models.TextField(max_length=45, unique=True)),
                ('Correo', models.EmailField(max_length=75, unique=True)),
                ('Contraseña', models.TextField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('Genero', models.CharField(max_length=1)),
                ('Intentos', models.IntegerField(default=0)),
                ('Contactos', models.ManyToManyField(through='registro.Tiene', to='registro.contacto')),
                ('Roles', models.ManyToManyField(to='registro.rol')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='tiene',
            name='IDUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro.usuario'),
        ),
        migrations.AddField(
            model_name='tiene',
            name='Telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro.contacto'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Log', models.DateTimeField(auto_now_add=True)),
                ('IDUsuario', models.ForeignKey(db_column='IDUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='registro.usuario')),
            ],
            options={
                'db_table': 'Log',
            },
        ),
    ]
