# Generated by Django 4.2.5 on 2023-10-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='IDUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Roles',
            field=models.ManyToManyField(db_table='Ejerce', to='registro.rol'),
        ),
    ]
