# Generated by Django 4.2.5 on 2023-10-06 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_log_idusuario_alter_usuario_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Roles',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.rol'),
        ),
    ]
