# Generated by Django 4.2.5 on 2023-10-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_remove_usuario_roles_usuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Contactos',
        ),
        migrations.AlterField(
            model_name='log',
            name='IDUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Logs', to='registro.usuario'),
        ),
        migrations.AlterField(
            model_name='tiene',
            name='IDUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Contactos', to='registro.usuario'),
        ),
        migrations.AlterField(
            model_name='tiene',
            name='Telefono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Vinculos', to='registro.contacto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Tipo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuarios', to='registro.rol'),
        ),
    ]
